### ISSUE TITLE
Issue release zip for v11 please

### ISSUE THREAD

**Issue by platinum4** [nemosminer/ccminerKlausTyescrypt#5]
See subject line ty sir

**Comment by platinum4** [comment]
6 hours no zip file-- this is theft

**Comment by nemosminer** [comment]
theft?

**Comment by nemosminer** [comment]
compile it then...

**Comment by nemosminer** [comment]
v11 is linux compile fix support / no improvements over v10...

**Comment by platinum4** [comment]
Make v12 for Pascal cards better

**Comment by nemosminer** [comment]
trex is on to it...
