### ISSUE TITLE
1080ti intensity 12.75

### ISSUE THREAD

**Issue by Stargazer77** [nemosminer/ccminerKlausTyescrypt#6]
Hi! GTX1070 hashrate is 730H/s(560H/s on KlausT-8.23-r1) and   -i 12.5  give "Using intensity 12.406 (5760 threads)" its good result
 but  1080Ti 940-960H/s(975H/s on KlausT-8.23-r1)  -i 12.5 give "Using intensity 11.750 (3584 threads)   and -i 13 give  "Using intensity 12.750 (7168 threads)".   -i 13.3  not working.   Why 1080ti give bad result?

**Comment by nemosminer** [comment]
its very memory intensive try running with enlargement pill... should get better results.. 

use -i 12.5

**Comment by Stargazer77** [comment]
What kind of pill to enlargement and where to get it? I always use -i
12.5  but it does not work for 1080ti.


ср, 19 дек. 2018 г. в 22:35, nemo <notifications@github.com>:

**Comment by Stargazer77** [comment]
Can you write What kind of pill to enlargement and where to get it? Its a
pill for eth mining for 1080/1080ti? We have a many this cards and will be
very good if we can start them with a good result.

чт, 20 дек. 2018 г. в 18:54, nemo <notifications@github.com>:
